import { renderIcon } from '@/utils/index';
import {
  DashboardOutlined,
  SafetyCertificateOutlined,
  AppstoreOutlined,
  ShopOutlined,
  DeploymentUnitOutlined,
  MenuOutlined,
  DollarOutlined,
  TeamOutlined,
  SettingOutlined,
  InfoCircleOutlined,
  BankOutlined,
  VideoCameraOutlined,
  HistoryOutlined,
  MessageOutlined,
  SnippetsOutlined,
  WindowsOutlined,
  ShoppingCartOutlined,
  FileTextOutlined,
  GlobalOutlined,
  UserOutlined,
  CreditCardOutlined,
  CloudUploadOutlined,
  CloudOutlined,
  ApartmentOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FileOutlined,
  FilePdfOutlined,
  FileImageOutlined,
  FileWordOutlined,
  FileExcelOutlined,
  FilePptOutlined,
  FileZipOutlined,
  CustomerServiceOutlined,
  SolutionOutlined,
  CommentOutlined,
  StarOutlined,
  PhoneOutlined,
  BarChartOutlined,
  ScheduleOutlined,
  SmileOutlined,
  BookOutlined,
} from '@vicons/antd';

//前端路由图标映射表
export const constantRouterIcon = {
  DashboardOutlined: renderIcon(DashboardOutlined),
  SafetyCertificateOutlined: renderIcon(SafetyCertificateOutlined),
  AppstoreOutlined: renderIcon(AppstoreOutlined),
  ShopOutlined: renderIcon(ShopOutlined),
  DeploymentUnitOutlined: renderIcon(DeploymentUnitOutlined),
  MenuOutlined: renderIcon(MenuOutlined),
  DollarOutlined: renderIcon(DollarOutlined),
  TeamOutlined: renderIcon(TeamOutlined),
  SettingOutlined: renderIcon(SettingOutlined),
  InfoCircleOutlined: renderIcon(InfoCircleOutlined),
  BankOutlined: renderIcon(BankOutlined),
  VideoCameraOutlined: renderIcon(VideoCameraOutlined),
  HistoryOutlined: renderIcon(HistoryOutlined),
  MessageOutlined: renderIcon(MessageOutlined),
  SnippetsOutlined: renderIcon(SnippetsOutlined),
  WindowsOutlined: renderIcon(WindowsOutlined),
  ShoppingCartOutlined: renderIcon(ShoppingCartOutlined),
  FileTextOutlined: renderIcon(FileTextOutlined),
  GlobalOutlined: renderIcon(GlobalOutlined),
  UserOutlined: renderIcon(UserOutlined),
  CreditCardOutlined: renderIcon(CreditCardOutlined),
  CloudUploadOutlined: renderIcon(CloudUploadOutlined),
  CloudOutlined: renderIcon(CloudOutlined),
  ApartmentOutlined: renderIcon(ApartmentOutlined),
  FolderOutlined: renderIcon(FolderOutlined),
  FolderOpenOutlined: renderIcon(FolderOpenOutlined),
  FileOutlined: renderIcon(FileOutlined),
  FilePdfOutlined: renderIcon(FilePdfOutlined),
  FileImageOutlined: renderIcon(FileImageOutlined),
  FileWordOutlined: renderIcon(FileWordOutlined),
  FileExcelOutlined: renderIcon(FileExcelOutlined),
  FilePptOutlined: renderIcon(FilePptOutlined),
  FileZipOutlined: renderIcon(FileZipOutlined),
  CustomerServiceOutlined: renderIcon(CustomerServiceOutlined),
  SolutionOutlined: renderIcon(SolutionOutlined),
  CommentOutlined: renderIcon(CommentOutlined),
  StarOutlined: renderIcon(StarOutlined),
  PhoneOutlined: renderIcon(PhoneOutlined),
  BarChartOutlined: renderIcon(BarChartOutlined),
  ScheduleOutlined: renderIcon(ScheduleOutlined),
  SmileOutlined: renderIcon(SmileOutlined),
  BookOutlined: renderIcon(BookOutlined),
};
